### ISSUE TITLE
"Scene" - what is it?

### ISSUE THREAD

**Issue by 0anion0** [cgwire/gazu#151]
In kitsu-web I can create the episodes, the sequences, and shots.
In gazu 
What does "Scene" mean in Gazu?

"sequences" is the rendering result?

**Comment by frankrousseau** [comment]
It's a concept that is interesting mainly when you do asset management. For some very qualitative production, like video game trailers, you don't know what will be your shots and sequences. You build beautiful compositions (scenes), then you cut them into sequences and shots. 
From a production point of view, it's not interesting because you track final deliveries (assets and shots). But from the file perspective, it's important to be able to track what is happening prior to define precisely the shots.
In other terms, it's aimed to be used for very specific workflows (short and very qualitative movies). If you do something a bit more industrial, you should ignore this concept.
