### ISSUE TITLE
Email gotten even when user has not the permissions 

### ISSUE THREAD

**Issue by dragonbleapiece** [cgwire/gazu#255]
According to user permissions, `gazu.person.get_person` doesn't return emails. But fetching the persons via project team returns the email : `gazu.client.fetch_all(gazu.client.url_path_join("projects", project_id, "team"))`.
The role was Supervisor during the tests.

**Comment by EvanBldy** [comment]
Hi @dragonbleapiece,
Thanks for the report!
It should fixed in this commit https://github.com/cgwire/zou/commit/be8a0176e11f4b1a6bf5e2382a3ef54f25f26b19.
It's already in the latest release. 
I also have added a function to do that in this PR : https://github.com/cgwire/gazu/pull/261
Can you retry and close the issue if it works fine ?
Have a nice day
