### ISSUE TITLE
add_preview(): Upload works but script crashes

### ISSUE THREAD

**Issue by Tilix4** [cgwire/gazu#89]
Based on https://github.com/cgwire/cgwire-demo script.

Using `preview_file = gazu.task.add_preview(
            task_sb,
            comment,
            file_paths_sb[index]
        )` to upload a '.mp4' file (works as expected with a '.png') uploads the file, I'm able to see the revision on the task, but rises the following error:

> File "demo.py", line 365, in <module>
    file_paths_sb[index]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gazu/task.py", line 573, in add_preview
    client.upload(path, preview_file_path)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gazu/client.py", line 313, in upload
    url, headers=make_auth_header(), files=files
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

##### Lead:
I get a `504 Gateway Time-out` from nginx.

**Comment by flablog** [comment]
The issue is here : 
https://github.com/cgwire/gazu/blob/d250cbe62122d1e29ee5c8dd7b1818839b965042/gazu/task.py#L571

When uploading a movie, the dict should be like that 
`{'is_movie': True}` instead of {}
But that function don't ask or detects if it's a movie or not.

I never used that function, that's why I haven't see the bug before. Here is my obsolete (but still working) method:
You need to get your task["id"]
1. Publish (or get) a comment, for example :
`comment = gazu.client.post("/actions/tasks/%s/comment" % task["id"], data)`
2. Then create the preview to the linked comment specifying it's a movie
`post = gazu.client.post('/actions/tasks/%s/comments/%s/add-preview' % (task["id"], comment["id"]), {'is_movie': movie})`
3. Finaly, upload the file to the preview
`upload = gazu.client.upload('pictures/preview-files/%s' % post['id'], filepath)`

**Comment by frankrousseau** [comment]
Hello,

Thank you @flablog for taking the time to answer. The script is totally fine and the `is_movie` flag is not needed anymore. 

The problem comes from the Nginx config. The video processing requires a lot of time. Which leads Nginx to a timeout.

Can you add these lines to the Nginx configuration file?

```
    location /api {
        ...
        proxy_connect_timeout 600s;
        proxy_send_timeout 600s;
        proxy_read_timeout 600s;
        send_timeout 600s;
}
```

**Comment by Tilix4** [comment]
Adding these lines to Nginx configuration file and then restarting the service made it work correctly.
Thanks!
